---
title: "Module XX: Linear Models and Linear Monsters"
format:
  revealjs:
    toc: false
---

```{r}
#| label: setup
#| include: false

library(printr)
```

## Learning goals

1. Fit basic linear and generalized linear models including models for counts.
1. Fit GLMs with interaction terms.
1. Fit GLMs with random effects using `lme4`.

Optional topics:
1. Fit GLMs with spline terms using `mgcv`.
1. Fit binomial and overdispersed binomial models, and compare them to bernoulli models on the same data.
1. Understand the limitations of frequentist linear models and know that `brms` exists.

## Some notes

- Throughout this course, we're attempted to use relatively few datasets in order to minimize confusion.
- When trying to show off many different features of data, this is not so easy. Most regression models in real life do not need all of these features at one time, and they are easier to discuss separately.
- So we have a choice ahead of us: we can either introduce many different datasets, or use a completely fabricated dataset where we know the truth and can ensure that these statistical problems are present.
- We have elected for the latter solution, except for the final section on binomial models.

## (Simulated) city cases dataset

- Suppose the Queen of Caldwych is holding court in her capital city of Hightwell when her Royal Chief Epidemiologist (you can pretend that's you, if you want) tells her, "Your Grace! I fear the grimbleth in our nation's water supply is a cause of excess cases of Klaron's gortensia beyond what can be explained by other factors!"
- Being a kind and benevolent monarch, the Queen immediately commissions a 3 year prospective study to identify all incident cases of Klaron's gortensia in a spatially representative sample of 23 cities in Caldwych, including Hightwell. She also provides funding for a representative sampling of the concentration of grimbleth in the municipal drinking water supply using the latest and greatest assay that can detect parts per million to the nearest hundreth accurately.
- You can also assume the temperature and population measurements are completely accurate.
- You know that Klaron's gortensia is a chronic multifactorial condition with no single deterministic cause. Several environmental, (epi)genetic, and time-varying exposures can contribute to the development of Klaron's gortensia. You can assume that we have a 100\% accurate diagnostic method for Klaron's gortensia 


## Interactions {.scrollable}

## Random effects {.scrollable}

## Splines {.scrollable}

## Bayesian models {.scrollable}

## Binomial models {.scrollable}
