project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "SISMID R for ID Materials (2025)"
  sidebar:
    style: docked
    search: true
    pinned: true
    tools: 
      - icon: github
        href: https://github.com/wzbillings/SISMID-2025
    contents: 
      - text: "Welcome!"
        href: index.qmd
      - text: "Course Schedule"
        href: schedule.qmd
      - text: "Course Resources"
        href: references.qmd
      - section: "Day 1"
        contents:
          - href: modules/Module00-Welcome.qmd
            target: _blank
          - href: modules/Module01-Intro.qmd
            target: _blank
          - href: modules/Module02-Functions.qmd
            target: _blank
          - href: modules/Module03-WorkingDirectories.qmd
            target: _blank
          - href: modules/Module04-RProject.qmd
            target: _blank
          - href: modules/Module05-DataImportExport.qmd
            target: _blank
          - href: modules/Module06-DataSubset.qmd
            target: _blank
          - href: modules/Module07-VarCreationClassesSummaries.qmd
            target: _blank
      - section: "Day 2"
        contents:
          - href: modules/Module08-DataMergeReshape.qmd
            target: _blank
          - href: modules/Module09-DataAnalysis.qmd
            target: _blank
          - href: modules/Module095-DataAnalysisWalkthrough.qmd
            target: _blank
          - href: modules/Module10-DataVisualization.qmd
            target: _blank
      - section: "Day 3"
        contents:
          - href: modules/Module11-RMarkdown.qmd
            target: _blank
          - href: modules/Module12-Iteration.qmd
            target: _blank
          - href: modules/Module13-Functions.qmd
            target: _blank
  repo-url: https://github.com/wzbillings/SISMID-2025
  reader-mode: true

# Default for table of contents
toc: true
toc-title: Page Items
toc-location: right

# Default knitr options
execute:
  echo: true
  message: true
  warning: true
  freeze: auto

engine: knitr

# Default author
author:
  - name: "Alex Edwards"
    url: https://sph.emory.edu/profile/faculty/alex-edwards
  - name: "Zane Billings"
    url: https://wzbillings.com/

# Default fields for citation
license: "CC BY-NC"

format:
  html:
    theme:
      light: [cosmo, format/_fonts.scss, format/_light.scss, format/_callouts.scss]
      dark: [cosmo, format/_fonts.scss, format/_dark.scss, format/_callouts.scss]
    grid:
      sidebar-width: 270px
      body-width: 1000px
      margin-width: 200px
      gutter-width: 1rem
    code-copy: true
    code-fold: show
    code-overflow: wrap
    code-link: true
    code-tools: true
    code-line-numbers: true

# Extension Lua filters
filters:
  - line-highlight
