---
title: Course Resources
bibliography: SISMID-Module.bib
nocite: "@*"
---

# Data and Exercise downloads

* Download all datasets here: [click to download](./downloads/data.zip).
* Download all exercises and solution files here: [click to download](./downloads/exercises.zip)
* Download all slide decks here: [click to download](./downloads/modules.zip)
* Get the example R Markdown document for Module 11 here: [click to download](./modules/Module11-Rmarkdown-Demo.Rmd){target="_blank"}
    - And the sample bibligraphy "bib" file is here: [click to download](./modules/example-bib.bib){target="_blank"}
    - And the rendered HTML file is here: [click to download](./modules/Module11-Rmarkdown-Demo.html){target="_blank"}
* Course GitHub where all materials can be found (to download the entire course as a zip file click the green "Code" button): [https://github.com/UGA-IDD/SISMID-2024](https://github.com/UGA-IDD/SISMID-2024){target="_blank"}.

# Useful (+ Free) Resources

- R for Data Science: http://r4ds.had.co.nz/  
(great general information)
- Fundamentals of Data Visualization: https://clauswilke.com/dataviz/ 
- R for Epidemiology: https://www.r4epi.com/
- The Epidemiologist R Handbook: https://epirhandbook.com/en/
- R basics by Rafael A. Irizarry: https://rafalab.github.io/dsbook/r-basics.html
(great general information)
- Open Case Studies: https://www.opencasestudies.org/  
(resource for specific public health cases with statistical implementation and interpretation)

# Need help?

- Various "Cheat Sheets": [https://github.com/rstudio/cheatsheets/](https://github.com/rstudio/cheatsheets/)
- R reference card: [http://cran.r-project.org/doc/contrib/Short-refcard.pdf](http://cran.r-project.org/doc/contrib/Short-refcard.pdf)  
- R jargon: [https://link.springer.com/content/pdf/bbm%3A978-1-4419-1318-0%2F1.pdf](https://link.springer.com/content/pdf/bbm%3A978-1-4419-1318-0%2F1.pdf)
- R vs Stata: [https://link.springer.com/content/pdf/bbm%3A978-1-4419-1318-0%2F1.pdf](https://link.springer.com/content/pdf/bbm%3A978-1-4419-1318-0%2F1.pdf)
- R terminology: [https://cran.r-project.org/doc/manuals/r-release/R-lang.pdf](https://cran.r-project.org/doc/manuals/r-release/R-lang.pdf)


# Other references {.unnumbered}

::: {#refs}
:::
